version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend/data:/app/data
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "http://localhost:5001"
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend
    volumes:
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules: